### ISSUE TITLE
Controlling where RTD extras are injected

### ISSUE THREAD

**Issue by bintoro** [rtfd/readthedocs-sphinx-ext#19]
As discussed in https://github.com/snide/sphinx_rtd_theme/issues/117, the theme stylesheet gets inserted *after* custom CSS declarations, making CSS overrides more complicated than they need to be.

How about using the existing `extrahead` template block if it's present and only injecting at the end of `<head>` if the placeholder has been removed?

It would then be trivial to fix the stylesheet cascading directly in the theme by moving `extrahead` up a little.

**EDIT:**

Actually, it's not clear to me why the theme stylesheet even needs to be part of the monkey patch. After figuring out what `theme_css` should be, the extension could just prepend it to `context['css_files']`.

**Comment by agjohnson** [comment]
Injecting into `extrahead` is a template level manipulation that requires us to override `layout.html`. Avoiding this override entirely is the point of moving the integration to this module.

Prepending to `css_files` might be possible. We hit a number of edge cases working with templates at this level however, I don't recall the case that broke this usage. Worth exploring again at least.

**Comment by bintoro** [comment]
I wasn't trying to suggest templating as a substitute for patching the rendered HTML.

To illustrate, instead of

```python
# Handle original render function
content = old_render(template, render_context)
end_body = content.lower().find('</head>')

# Insert our content at the end of the body.
if end_body != -1:
    content = content[:end_body] + rtd_content + content[end_body:]
else:
    app.debug("File doesn't look like HTML. Skipping RTD content addition")

return content
```

we'd have something like

```python
# Handle original render function
content = old_render(template, render_context)
patch_position = content.find('<!--rtd_extras-->')
if patch_position == -1:
    patch_position = content.lower().find('</head>')
if patch_position == -1:
    app.debug("File doesn't look like HTML. Skipping RTD content addition")
else:
    # Insert our content
    content = content[:patch_position] + rtd_content + content[patch_position:]

return content
```

That is, look for the placeholder (which would exist in unmodified and properly modified RTD themes) and fall back to patching `<head>` otherwise.

Repurposing the existing `extrahead` thing wasn't central to the idea. It's actually much simpler to just add a new placeholder in the theme.

**Comment by ericholscher** [comment]
I've updated this with #20 so that we include our theme CSS in the `css_files`, and only inject javascript. This should make custom themes easier to handle, as long as they use the `css_files` attribute in Sphinx.

**Comment by bintoro** [comment]
Sweet! :rocket:
