### ISSUE TITLE
[Bug] Google Analytics is being missed

### ISSUE THREAD

**Issue by AnastasiaNovikova** [rtfd/readthedocs-sphinx-ext#21]
Hello dear dev team!
we have the same issue with GA as Roman - https://github.com/rtfd/readthedocs.org/issues/2077
Our documentation is build on Sphinx, so we decided to address this issue here...
could you help? =)

Our project - cityadsuserdocs.readthedocs.org
our GA key - UA-76246843-1
Ps. we going to host translations to our docs, may be it's important for this issue...

**Comment by stsewd** [comment]
Closing as stale, but feel free to reopen with more information (rtd project url) if you still have this problem
