### ISSUE TITLE
Failing sphinx autoclass documentation build. 

### ISSUE THREAD

**Issue by Omkar20895** [rtfd/readthedocs-sphinx-ext#23]
Hi there, 
- I have been using sphinx autoclass to automatically build my documentation online, you can find the documentation [here](http://podaacpy.readthedocs.io/en/latest/).
- Recently the documentation builds have started failing for some reason that I could not find out. The build is successful in my local machine but it fails online and there is no documentation that appears online. 
- The build fails mainly in the fails [webservices.rst](https://github.com/lewismc/podaacpy/blob/master/docs/source/webservices.rst), [utilities.rst](https://github.com/lewismc/podaacpy/blob/master/docs/source/utilities.rst) and [mcc.rst](https://github.com/lewismc/podaacpy/blob/master/docs/source/mcc.rst)
- You can find my repository [here](https://github.com/lewismc/podaacpy).
- You can also find further reference to this issue [here](https://github.com/lewismc/podaacpy/issues/14).

Please look into this issue. Any suggestions or help will be helpful. Thanks.

**Comment by lewismc** [comment]
Thanks for registering @Omkar20895, to add more detail here there appears to be no output in the build log to suggest that there is a syntax issue so we ( @Omkar20895 and I) are kinda scratching out heads on this one. Any suggestions for what is wrong with the documentation would be greatly appreciated. Thanks

**Comment by ericholscher** [comment]
I tried to reproduce it, but the build passed the last 2 times I ran it.. http://readthedocs.org/projects/podaacpy/builds/

I'll see if I can make it fail so I can see what the issue is.

**Comment by Omkar20895** [comment]
@ericholscher Thanks for looking into this, the build does not show any errors, but the html documentation is missing in the pages mentioned above for some unknown reason.

**Comment by ericholscher** [comment]
The build seems to be missing a beautifulsoup dependency:

```
/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/checkouts/latest/docs/source/introduction.rst:38: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/checkouts/latest/docs/source/utilities.rst:22: WARNING: autodoc: failed to import class u'PodaacUtils' from module u'podaac_utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/checkouts/latest/podaac/podaac_utils.py", line 18, in <module>
    from bs4 import BeautifulSoup as bs
ImportError: No module named bs4
/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/checkouts/latest/docs/source/webservices.rst:22: WARNING: autodoc: failed to import class u'Podaac' from module u'podaac_data_source'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/podaacpy/checkouts/latest/podaac/podaac_data_source.py", line 18, in <module>
    from bs4 import BeautifulSoup as bs
ImportError: No module named bs4
```

Do you have your requirements properly specified?

**Comment by ericholscher** [comment]
I went ahead and flipped the `install project` setting for your project, I think that will likely resolve this issue, as it will install your reps from `setup.py`.

**Comment by Omkar20895** [comment]
@ericholscher thank you very much for your help! Everything is working great! Thanks.

**Comment by Omkar20895** [comment]
@ericholscher we have recently pushed some commits into the master and again the documentation problem popped out of no where. Please refer to [this](https://github.com/lewismc/podaacpy/issues/73). Please let us know where the problem is, thanks.

@lewismc

**Comment by stsewd** [comment]
Looks like the related issue is closed, feel free to reopen if the problem persists.
