### ISSUE TITLE
css_files is deprecated 

### ISSUE THREAD

**Issue by Blendify** [rtfd/readthedocs-sphinx-ext#35]
`builder.css_files` is deprecated we should use `add_stylesheet()`

Note `script_files` might also become deprecated see https://github.com/sphinx-doc/sphinx/issues/4439

**Comment by stsewd** [comment]
RTD always insert the css_files at the beginning https://github.com/rtfd/readthedocs-sphinx-ext/blob/c158320f83affd15a43ea4ac1b0bb2a47e28ab54/readthedocs_ext/readthedocs.py#L83-L84

What I understand `add_stylesheet()` inserts at the end, right?

**Comment by Blendify** [comment]
CSS files should always be inserted at the beginning of the HTML file in the head tag or is this not what you mean?

**Comment by stsewd** [comment]
I mean the order of the link tags containing the css, I think rtd always insert those first to avoid override the ones from the user.
