### ISSUE TITLE
Extension requires jinja2>=2.9

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs-sphinx-ext#69]
We are using the `tojson` filter #66 

http://jinja.pocoo.org/docs/2.10/templates/#tojson

But it's only available in jinja2>=2.9.

Sphinx supports `jinja2>=2.3` since 1.0

But some users may depend on a lower version of jinja?

**Comment by ericholscher** [comment]
Let's put this in our requirements at least, so that users have to explicitly overwrite it?

**Comment by stsewd** [comment]
@ericholscher do you mean the core requirements that are installed in rtd? Or as a dependency of the package itself?

**Comment by ericholscher** [comment]
I think it would have the same effect, so probably the package.
